const EVENTS = {
  ALL: "ALL",
  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT",
  LOG_IN_REQUESTED: "LOG_IN_REQUESTED",
  ROUTE_CHANGE: "ROUTE_CHANGE",
  CLOSE: "CLOSE",
  LOADED: "LOADED"
};

module.exports = EVENTS;
